[package]
name = "iotedged"
version = "0.1.0"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2018"

[dependencies]
base64 = "0.12"
chrono = "0.4"
foreign-types-shared = "0.1"
hyper = "0.13"
hyper-openssl = "0.8"
openssl = "0.10"
percent-encoding = "2"
rand = "0.7"
serde_json = "1"
tokio = { version = "0.2", features = ["dns", "macros"] }
url = "2"

cs-client-async = { path = "../cs-client-async" }
http-common = { path = "../http-common" }
ks-client = { path = "../ks-client" }
ks-client-async = { path = "../ks-client-async" }
ks-common = { path = "../ks-common" }
openssl2 = { path = "../../openssl-pkcs11-demo/openssl2" }
openssl-engine-ks = { path = "../openssl-engine-ks" }
openssl-sys2 = { path = "../../openssl-pkcs11-demo/openssl-sys2" }
