[package]
name = "iotedged"
version = "0.1.0"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2018"

[dependencies]
base64 = "0.12"
chrono = "0.4"
foreign-types-shared = "0.1"
openssl = "0.10"
openssl-sys = "0.9"
percent-encoding = "2"
rand = "0.7"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde_json = "1"
url = "2"

ks-client = { path = "../ks-client" }
ks-common = { path = "../ks-common" }
ksd = { path = "../ksd" }
openssl2 = { path = "../../openssl-pkcs11-demo/openssl2" }
openssl-engine-ks = { path = "../openssl-engine-ks" }
openssl-sys2 = { path = "../../openssl-pkcs11-demo/openssl-sys2" }
