[workspace]
members = [
	"cert/aziot-cert-client-async",
	"cert/aziot-cert-common",
	"cert/aziot-cert-common-http",
	"cert/aziot-certd",

	"http-common",

	"iotedged",

	"key/aziot-key-client",
	"key/aziot-key-client-async",
	"key/aziot-key-common",
	"key/aziot-key-common-http",
	"key/aziot-keyd",
	"key/aziot-keys",
]
