[package]
name = "cs-common-http"
version = "0.1.0"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }

ks-common = { path = "../ks-common" }
